plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: echo "${releases.version}" > version.txt
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"

  - "gradle-semantic-release-plugin"
  - -  "@semantic-release/git"
    - assets:
        - gradle.properties
        - CHANGELOG.md
        - version.txt
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
