plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
    #  - - "@semantic-release/exec"
    #    - verifyReleaseCmd: 'mvn versions:set -DnewVersion="${nextRelease.version}" && echo "NEXT_VERSION=${nextRelease.version}" >> build.env'
  - "gradle-semantic-release-plugin"
  - -  "@semantic-release/git"
    - assets:
        - gradle.properties
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"