name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/commit-analyzer
        npm install -g @semantic-release/release-notes-generator
        npm install -g @semantic-release/exec
        npm install -g @semantic-release/git
        npm install -g @semantic-release/gradle-semantic-release-plugin
        npm i -g gradle-semantic-release-plugin
        npm i -g semantic-release-monorepo                                                                                                                                                                                                           npm install -g semantic-release-gradle
        npm install -g @semantic-release/changelog

    - name: Run semantic-release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}